name: "Bug Report"
description: "Report a reproducible bug with steps, expected vs actual behavior, and any stack traces."
title: "[BUG] {{ summary }}"
labels: ["bug"]
assignees: []
body:
  - type: input
    id: summary
    attributes:
      label: "📝 Summary"
      description: "A brief, one-line summary of the bug. This will be used as the issue title."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "🪜 Steps to Reproduce"
      description: |
        Provide numbered steps to reproduce the issue. Example:
        1. Go to `/signup`
        2. Enter `user@`
        3. Click **Create Account**
        4. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "✅ Expected Behavior"
      description: "Describe the expected behavior when following the steps above. Be specific (e.g., UI change, HTTP response code)."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "❌ Actual Behavior"
      description: "Describe the actual behavior, including error messages, HTTP codes, visible failures. Paste exact errors where possible."
    validations:
      required: true

  - type: textarea
    id: stack_trace
    attributes:
      label: "🔎 Stack Trace (if applicable)"
      description: "Paste any relevant stack traces or error logs here. Wrap in triple backticks for readability."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **📎 Attachments**

        Attach screenshots, logs, or any relevant files using the **Attach files** button below the issue form. Please do not paste large binary files directly in the text fields.

        Helpful attachments might include:
        - Screenshots showing the UI error
        - Console logs or network traces exported to a file
        - A link to a minimal reproducible repo or CodePen/StackBlitz if available
